// every enum here MUST have a number or the watcher will break
// and NEVER reassign or change numbers
export enum EventName {

    // member run time events, only generated by client
    member_entered = 1000,
    member_left = 1010,
    member_moved = 1020,
    member_observed = 1030,
    member_changed_mic_pref = 1040,
    member_changed_nickname = 1050,
    member_damaged = 1060,
    member_died = 1070,
    member_respawned = 1080,
    // design time events, generated by client of api
    entity_created = 2200,

    entity_transformed = 4000,
    entity_translated = 4010,
    entity_rotated = 4020,
    entity_scaled = 4030,
    entity_colored = 4040,
    entity_deleted = 4050,
    entity_animated_offset = 4060,
    // entity_locked = 405,
    // entity_unlocked = 406,
    // entity_set_interactable = 407,
    // entity_unset_interactable = 408,
    // entity_set_physics = 409,
    // entity_unset_physics = 410

    // run time interactions with an entity
    entity_grabbed = 5000,
    entity_released = 5010,
    entity_trigger_squeezed = 5020,
    entity_collected = 5030,
    hud_message_broadcasted = 6000,

    agent_spawned = 7000,
    agent_directed = 7100,
    agent_hit = 7200,

    target_hit = 8000




}
