// every enum here MUST have a number or the watcher will break
// and NEVER reassign or change numbers
export enum EventName {

    // member run time events, only generated by client
    member_entered = 100,
    member_left = 101,
    member_moved = 102,
    member_observed = 103,
    member_changed_mic_pref = 104,
    member_changed_nickname = 105,
    member_damaged = 106,
    // design time events, generated by client of api
    spawn_point_created = 200,
    box_created = 210,
    cone_created = 211,
    sphere_created = 212,
    plane_created = 213,
    cylinder_created = 214,
    grid_created = 215,
    floor_created = 216,
    wall_created = 217,
    ribbon_created = 218,
    line_path_created = 219,

    light_created = 300,
    light_intensity_set = 301,
    light_property_set = 302,

    entity_transformed = 400,
    entity_translated = 401,
    entity_rotated = 402,
    entity_scaled = 403,
    entity_colored = 404,
    entity_deleted = 405,
    // entity_locked = 405,
    // entity_unlocked = 406,
    // entity_set_interactable = 407,
    // entity_unset_interactable = 408,
    // entity_set_physics = 409,
    // entity_unset_physics = 410

    // run time interactions with an entity
    entity_grabbed = 500,
    entity_released = 501,
    entity_trigger_squeezed = 502,
    hud_message_broadcasted = 600,

    //complex entities
    lever_created = 700,
    door_created = 701,
    bridge_console_created = 702,
    fighter_jet_console_created = 703,

    //spawners - gives ongoing constant supply
    // maybe even tools like markers, spray cans, etc.
    key_spawner_created = 800,
    gun_spawner_created = 802,
    ammo_spawner_created = 803,
    health_spawner_created = 804,
    enemy_spawner_created = 805,

}
