
# UPDATE event-names.ts INSTEAD OF THIS FILE
# THIS FILE IS AUTOGENERATED, DO NOT MANUALLY UPDATE
#
defmodule EventName do

  def member_entered, do: 1
  def member_left, do: 2
  def member_moved, do: 3
  def member_observed, do: 4
  def member_changed_mic_pref, do: 5
  def member_changed_nickname, do: 6
  def member_damaged, do: 7
  def entity_created, do: 8
  def entity_transformed, do: 9
  def entity_colored, do: 10
  def entity_deleted, do: 11
  def entity_grabbed, do: 12
  def entity_released, do: 13
  def entity_trigger_squeezed, do: 14
  def message_broadcasted, do: 15
  def agent_placed, do: 16
  def agent_path_planned, do: 17
  def agent_removed, do: 18

end
        