
# UPDATE event-names.ts INSTEAD OF THIS FILE
# THIS FILE IS AUTOGENERATED, DO NOT MANUALLY UPDATE
#
defmodule EventName do

  def int_to_atom(100), do: :member_entered
  def int_to_atom(101), do: :member_left
  def int_to_atom(102), do: :member_moved
  def int_to_atom(103), do: :member_observed
  def int_to_atom(104), do: :member_changed_mic_pref
  def int_to_atom(105), do: :member_changed_nickname
  def int_to_atom(106), do: :member_damaged
  def int_to_atom(200), do: :spawn_point_created
  def int_to_atom(210), do: :box_created
  def int_to_atom(211), do: :cone_created
  def int_to_atom(212), do: :sphere_created
  def int_to_atom(213), do: :plane_created
  def int_to_atom(214), do: :cylinder_created
  def int_to_atom(215), do: :grid_created
  def int_to_atom(216), do: :floor_created
  def int_to_atom(217), do: :wall_created
  def int_to_atom(218), do: :ribbon_created
  def int_to_atom(219), do: :line_path_created
  def int_to_atom(220), do: :entity_created
  def int_to_atom(300), do: :light_created
  def int_to_atom(301), do: :light_intensity_set
  def int_to_atom(302), do: :light_property_set
  def int_to_atom(400), do: :entity_transformed
  def int_to_atom(401), do: :entity_translated
  def int_to_atom(402), do: :entity_rotated
  def int_to_atom(403), do: :entity_scaled
  def int_to_atom(404), do: :entity_colored
  def int_to_atom(405), do: :entity_deleted
  def int_to_atom(500), do: :entity_grabbed
  def int_to_atom(501), do: :entity_released
  def int_to_atom(502), do: :entity_trigger_squeezed
  def int_to_atom(600), do: :hud_message_broadcasted
  def int_to_atom(700), do: :lever_created
  def int_to_atom(701), do: :door_created
  def int_to_atom(702), do: :bridge_console_created
  def int_to_atom(703), do: :fighter_jet_console_created
  def int_to_atom(800), do: :key_spawner_created
  def int_to_atom(802), do: :gun_spawner_created
  def int_to_atom(803), do: :ammo_spawner_created
  def int_to_atom(804), do: :health_spawner_created
  def int_to_atom(805), do: :enemy_spawner_created

  def atom_to_int(:member_entered), do: 100
  def atom_to_int(:member_left), do: 101
  def atom_to_int(:member_moved), do: 102
  def atom_to_int(:member_observed), do: 103
  def atom_to_int(:member_changed_mic_pref), do: 104
  def atom_to_int(:member_changed_nickname), do: 105
  def atom_to_int(:member_damaged), do: 106
  def atom_to_int(:spawn_point_created), do: 200
  def atom_to_int(:box_created), do: 210
  def atom_to_int(:cone_created), do: 211
  def atom_to_int(:sphere_created), do: 212
  def atom_to_int(:plane_created), do: 213
  def atom_to_int(:cylinder_created), do: 214
  def atom_to_int(:grid_created), do: 215
  def atom_to_int(:floor_created), do: 216
  def atom_to_int(:wall_created), do: 217
  def atom_to_int(:ribbon_created), do: 218
  def atom_to_int(:line_path_created), do: 219
  def atom_to_int(:entity_created), do: 220
  def atom_to_int(:light_created), do: 300
  def atom_to_int(:light_intensity_set), do: 301
  def atom_to_int(:light_property_set), do: 302
  def atom_to_int(:entity_transformed), do: 400
  def atom_to_int(:entity_translated), do: 401
  def atom_to_int(:entity_rotated), do: 402
  def atom_to_int(:entity_scaled), do: 403
  def atom_to_int(:entity_colored), do: 404
  def atom_to_int(:entity_deleted), do: 405
  def atom_to_int(:entity_grabbed), do: 500
  def atom_to_int(:entity_released), do: 501
  def atom_to_int(:entity_trigger_squeezed), do: 502
  def atom_to_int(:hud_message_broadcasted), do: 600
  def atom_to_int(:lever_created), do: 700
  def atom_to_int(:door_created), do: 701
  def atom_to_int(:bridge_console_created), do: 702
  def atom_to_int(:fighter_jet_console_created), do: 703
  def atom_to_int(:key_spawner_created), do: 800
  def atom_to_int(:gun_spawner_created), do: 802
  def atom_to_int(:ammo_spawner_created), do: 803
  def atom_to_int(:health_spawner_created), do: 804
  def atom_to_int(:enemy_spawner_created), do: 805

end
        