# UPDATE event-names.ts INSTEAD OF THIS FILE
# THIS FILE IS AUTOGENERATED, DO NOT MANUALLY UPDATE
#
defmodule EventName do
  def int_to_atom(1), do: :member_entered
  def int_to_atom(2), do: :member_left
  def int_to_atom(3), do: :member_moved
  def int_to_atom(4), do: :member_observed
  def int_to_atom(5), do: :member_changed_mic_pref
  def int_to_atom(6), do: :member_changed_nickname
  def int_to_atom(7), do: :member_damaged
  def int_to_atom(8), do: :entity_created
  def int_to_atom(9), do: :entity_transformed
  def int_to_atom(10), do: :entity_colored
  def int_to_atom(11), do: :entity_deleted
  def int_to_atom(12), do: :entity_grabbed
  def int_to_atom(13), do: :entity_released
  def int_to_atom(14), do: :entity_trigger_squeezed
  def int_to_atom(15), do: :message_broadcasted
  def int_to_atom(16), do: :agent_placed
  def int_to_atom(17), do: :agent_path_planned
  def int_to_atom(18), do: :agent_removed

  def atom_to_int(:member_entered), do: 1
  def atom_to_int(:member_left), do: 2
  def atom_to_int(:member_moved), do: 3
  def atom_to_int(:member_observed), do: 4
  def atom_to_int(:member_changed_mic_pref), do: 5
  def atom_to_int(:member_changed_nickname), do: 6
  def atom_to_int(:member_damaged), do: 7
  def atom_to_int(:entity_created), do: 8
  def atom_to_int(:entity_transformed), do: 9
  def atom_to_int(:entity_colored), do: 10
  def atom_to_int(:entity_deleted), do: 11
  def atom_to_int(:entity_grabbed), do: 12
  def atom_to_int(:entity_released), do: 13
  def atom_to_int(:entity_trigger_squeezed), do: 14
  def atom_to_int(:message_broadcasted), do: 15
  def atom_to_int(:agent_placed), do: 16
  def atom_to_int(:agent_path_planned), do: 17
  def atom_to_int(:agent_removed), do: 18
end
